// This file is auto-generated by Convex codegen
// It will be regenerated during build on Vercel

export const api: {
  images: {
    addImage: any;
    getImages: any;
  };
} = {
  images: {
    addImage: null as any,
    getImages: null as any,
  },
} as any;
